// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnbqiuknnvcqhpouoztm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhuYnFpdWtubnZjcWhwb3VvenRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMDYwOTUsImV4cCI6MjA2NjU4MjA5NX0.ZHjBZuEsM6FmErHK-3culvSrfG1KSX3Hc1uOAHZToiQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);